import Head from "next/head";
import Layout from "../components/layout";

export default function Home() {
  return (
    <Layout>
      <div >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* {main}  */}
        <main>
          hello soy main
        </main>
        {/* {footer}  */}
        <footer>
          hello soy footer 
        </footer>
      </div>
     </Layout>
  );
}
